### ISSUE TITLE
/examples

### ISSUE THREAD

**Issue by pravosleva** [Gapur/algorithms#7]
Hello. Will you please, make `/examples` dir for life examples (for beginners).
(Имею ввиду практическое применение для разработанных классов и их методов).

**Comment by Gapur** [comment]
Hi Dan!
It is a great idea. Unfortunately, I am busy now with other projects. I don't have free time to provide this project with examples. But if you want to provide and improve this repository, feel free to create PR. Also, it is a good opportunity to learn how to work with open-source projects.
But You can learn a lot of information about algorithms with javascript on https://github.com/trekhleb/javascript-algorithms. It is a brilliant repository to learn.
Thanks. I hope you feel good.
